name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check secrets
        run: |
          echo "Server is set: ${{ secrets.FTP_SERVER != '' }}"
          echo "Username is set: ${{ secrets.FTP_USERNAME != '' }}"
          echo "Password is set: ${{ secrets.FTP_PASSWORD != '' }}"

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./wp-content/
          server-dir: /public_html/wp-content/